### ISSUE TITLE
AppImage

### ISSUE THREAD

**Issue by probonopd** [yousry/COOL-The-Game#1]
Is the [AppImage](http://appimage.org) for download somewhere? Thanks.

**Comment by yousry** [comment]
You can download it from here: [https://yousry.itch.io/cool](https://yousry.itch.io/cool).
Click:  Download Now. Choose:  No thanks, just take me to the downloads or select a Tip.

**Comment by probonopd** [comment]
Thanks @yousry. The AppImage does not run out-of-the-box on Ubuntu 16.04.

```
/tmp/.mount_4eaNAA/COOL: error while loading shared libraries: libGLEW.so.2.0: cannot open shared object file: No such file or directory
```

Please bundle all but [these](https://github.com/probonopd/AppImages/blob/master/excludelist) libraries inside the AppImage.

**Comment by yousry** [comment]
I updated the image according your list.  I now use the following scripts during my build: 
Collect all libraries: https://gist.github.com/yousry/cc138d4c0e030e112419522f72a533be and 
Remove included files: https://gist.github.com/yousry/57a46e0ada1436efa5bf1fe1fdefb960.
